name: Weather Forecast ETL Automation

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: 

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Copy .env file
    - name: Copy .env file
      run: cp .env /home/runner/work/weather-forecast-etl/.env

    # Step 5: Run the ETL pipeline
    - name: Run the ETL pipeline
      run: python etl/weather_forecast_etl.py
